name: tests
on:
  push:
  workflow_dispatch:


jobs:
  test-and-cover:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main

      #- uses: brokeyourbike/ocvalidate-action@v0.2
      #  with:
      #    opencore-version: '0.8.6'
      #    release: true
      #
      #- run: |
      #    ocvalidate "EFI/OC/config.plist" || exit 1

      - name: Get OC-Mod
        run: |
          # brew install curl jq

          ocmoddlurl=$(curl -s --location 'https://api.github.com/repos/wjz304/OpenCore_NO_ACPI_Build/releases/latest' | jq -r .assets[1].browser_download_url)
          curl -L ${ocmoddlurl} -o ocmod.zip
          unzip ocmod.zip -d ocmod

      - run: |
          ocmod/Utilities/ocvalidate/ocvalidate "EFI/OC/config.plist" || exit 1

      #- name: Delete workflow runs
      #  uses: Mattraks/delete-workflow-runs@v2
      #  with:
      #    retain_days: 1
      #    keep_minimum_runs: 3